import os
import time
import threading
from xmlrpc.client import ServerProxy, Binary
import requests

from rdkit import Chem
from openeye import oechem

from utils.misc import create_oeb_from_sdf, prompt_user
from .ShapeDatabaseServer import setup_server

def GetFormatExtension(fname):
    base, ext = os.path.splitext(fname.lower())
    if ext == ".gz":
        base, ext = os.path.splitext(base)
        ext += ".gz"
    return ext

class FastROCSSimilaritySearch():
    # TODO: Add Openeye license setup
    def __init__(self, lib_path: str, server_device: str = 'cuda:0', logger=None):
        self.logger = logger
        self._init_library(lib_path)
        self._setup_server(server_device)
        self.client = None

    def _init_library(self, lib_path: str):
        # Find or create .oeb file
        self.oeb_path = None
        if lib_path.endswith('.oeb'):
            self.oeb_path = lib_path
        elif lib_path.endswith('.sdf') or lib_path.endswith('.sdf.gz'):
            if self.logger is None or prompt_user(self.logger, f"Create .oeb file from {lib_path}?"):
                self.oeb_path = os.path.join(os.path.dirname(lib_path), f'database_{time.strftime("%Y%m%d_%H%M%S")}.oeb')
                if self.logger is not None and not prompt_user(self.logger, f"Use {self.oeb_path} as the output path?"):
                    while True:
                        self.logger.info(f"Please enter the output path: ")
                        self.oeb_path = input()
                        if not self.oeb_path.endswith('.oeb'):
                            self.logger.info(f"Please enter a valid .oeb file path")
                            continue
                        else:
                            break
                
                create_oeb_from_sdf([lib_path], self.oeb_path)
                if self.logger is not None: self.logger.info(f"Generated database file {self.oeb_path}")
            else:
                if self.logger is not None: self.logger.info(f"Aborting...")
                return False
        elif os.path.isdir(lib_path):
            # Check if there is a .oeb file in the directory
            for file in os.listdir(lib_path):
                if file.endswith('.oeb'):
                    # Remove temp.oeb file if it exists (half-baked oeb file generated by create_oeb_from_sdf)
                    if file == 'temp.oeb':
                        os.remove(os.path.join(lib_path, file))
                        continue
                    if self.logger is None or prompt_user(self.logger, f"Found database file {file} in {lib_path}, proceed with this database?"):
                        self.oeb_path = os.path.join(lib_path, file)
                    break
            
            # If no .oeb file found, scan directory content for .sdf.gz files
            if self.oeb_path is None:
                if self.logger is not None: self.logger.info(f"No database file found in {lib_path}, scanning directory content for .sdf.gz files")
                def get_sdf_files(lib_path):
                    sdf_files = []
                    for file in os.listdir(lib_path):
                        if file.endswith('.sdf.gz'):
                            sdf_files.append(os.path.join(lib_path, file))
                        elif os.path.isdir(os.path.join(lib_path, file)):
                            sdf_files += get_sdf_files(os.path.join(lib_path, file))
                    return sdf_files
                
                sdf_files = get_sdf_files(lib_path)
                if len(sdf_files) == 0:
                    if self.logger is not None: self.logger.info(f"No .sdf.gz files found in {lib_path}, aborting...")
                    return False
                
                total_size = sum([os.path.getsize(file) for file in sdf_files])
                if self.logger is not None: self.logger.info(f"Found {len(sdf_files)} .sdf.gz files in {lib_path}, total size: {total_size / 1024 / 1024:.2f} MB. ")
                if self.logger is None or prompt_user(self.logger, f"Proceed to generate .oeb file?"):
                    self.oeb_path = os.path.join(lib_path, f'database_{time.strftime("%Y%m%d_%H%M%S")}.oeb')
                    create_oeb_from_sdf(sdf_files, self.oeb_path)
                    if self.logger is not None: self.logger.info(f"Generated database file {self.oeb_path}")
                else:
                    if self.logger is not None: self.logger.info(f"Aborting...")
                    exit(1)
        else: 
            if self.logger is not None: self.logger.info(f"Invalid library path {lib_path}, aborting...")
            return False
        return True
    
    def _setup_server(self, server_device: str):
        self.server_device = server_device
        
        self.server_host = '0.0.0.0'
        self.server_port = 8080
        self.server_timeout = 300 # 5 minutes
        self.server_url = f"http://{self.server_host}:{self.server_port}"
        
        # Start server in a separate thread
        self.server_thread = threading.Thread(target=setup_server, kwargs={
            'oeb_path': self.oeb_path, 'device': self.server_device, 'hostname': self.server_host, 'port': self.server_port})
        self.server_thread.start()
        
        # Wait for server to be ready
        for _ in range(self.server_timeout):
            try:
                r = requests.get(self.server_url)
                if r.status_code == 200:
                    self.server_ready = True
                break
            except requests.exceptions.RequestException:
                time.sleep(1)
        else:
            raise Exception(f"Server not ready after {self.server_timeout} seconds")
        
        self.logger.info(f"Server is ready at {self.server_url}")
    
    def _setup_client(self):
        self.client = ServerProxy(self.server_url)
        self.logger.info(f"Client is ready at {self.server_url}")
    
    def _close_server(self):
        self.server_thread.join()
        self.logger.info(f"Server is closed")
    
    def search_topk(self, query_sdf: str, k: int = 10):
        if self.client is None:
            self._setup_client()
        
        fh = open(query_sdf, 'rb')
        data = Binary(fh.read())
        
        idx = self.client.SubmitQuery(data, k, '.sdf', '.sdf', {})
        while True:
            current, total = self.client.QueryStatus(idx, True)
            if total == 0:
                continue
            if current == total:
                break
            self.logger.info(f"Query progress: {current}/{total}")
            time.sleep(1)
        
        hist = self.client.QueryHistogram(idx)
        
        with open('temp.sdf', 'wb') as f:
            f.write(self.client.QueryResults(idx).data)
        results_provider = Chem.SDMolSupplier('temp.sdf')
        os.remove('temp.sdf')
        
        return [mol for mol in results_provider], hist
    
    def search_threshold(self, query_mol: Chem.Mol, threshold: float = 0.5):
        raise NotImplementedError("Not implemented")
    